import type { EntityProfile } from "@/lib/types";

const NOW = "2026-06-05T00:00:00Z";

const jupiterTimeline = [
  {
    date: "2021",
    title: "Mercurial spin-out",
    description: "Jupiter emerges from the Mercurial stablecoin-AMM project.",
  },
  {
    date: "2023-Q4",
    title: "Jupiter Perps launches",
    description: "Oracle-based perp DEX with the shared JLP pool goes live.",
  },
  {
    date: "2024-01",
    title: "JUP airdrop (Jupuary)",
    description: "First major JUP distribution to active users and stakers.",
  },
  {
    date: "2025",
    title: "Buyback era",
    description: ">$70M directed to open-market JUP buybacks; 50% revenue policy.",
  },
  {
    date: "2026-02",
    title: "ParaFi $35M + 'Going Green'",
    description: "Strategic JUP buy and net-zero-emissions governance proposal.",
  },
];

export const jupiterEntity: EntityProfile = {
  category: "Entity",
  slug: "jupiter",
  name: "Jupiter",
  symbol: "JUP",
  status: "APPROVED",
  tagline: "The everything exchange for Solana.",
  description:
    "Jupiter is Solana's largest DeFi aggregator and liquidity hub, routing swaps across every major Solana DEX and operating its own perpetuals, limit-order, DCA, and liquidity-provision products under one umbrella.",
  longDescription:
    "Jupiter began as a swap aggregator that finds the best execution path across Solana's fragmented liquidity, and has grown into a full product suite: Jupiter Swap (aggregation), Jupiter Perpetuals (up to 100x leverage on SOL/ETH/BTC against the shared JLP pool), Limit Orders, and DCA. The protocol is governed by the Jupiter DAO and its JUP token, with an aggressive supply-reduction and buyback program. Jupiter spun out of the Mercurial project and has expanded via acquisitions across the Solana stack (e.g. Meteora-adjacent liquidity tooling, mobile, and on-ramp partners).",
  differentiator:
    "Unlike single-product DEXs, Jupiter is a vertically integrated liquidity layer: the same team operates aggregation, a perp DEX, and the JLP liquidity pool, so order flow, fees, and JUP buybacks reinforce each other. JLP is real-yield (fees, not emissions) and JUP runs net-deflationary via burns + buybacks — a rare combination.",
  officialDocs: "https://dev.jup.ag/docs",
  website: "https://jup.ag",
  twitter: "https://x.com/JupiterExchange",
  discord: "https://discord.gg/jup",
  github: "https://github.com/jup-ag",

  components: [
    {
      name: "Jupiter Swap (Aggregation)",
      description:
        "Smart-routing aggregator that splits orders across Solana DEXs (Orca, Raydium, Meteora, etc.) for best execution and minimal price impact.",
    },
    {
      name: "Jupiter Perpetuals + JLP",
      description:
        "Oracle-based perp DEX offering up to 100x leverage on SOL, ETH, and BTC. Every trade is counterparty to the shared JLP liquidity pool, which earns 75% of perp fees.",
    },
    {
      name: "JUP Governance & Treasury",
      description:
        "JUP token holders steer tokenomics, buybacks, and treasury via the Jupiter DAO. 50% of on-chain revenue funds open-market buybacks.",
    },
  ],

  faq: [
    {
      question: "Is JLP a stablecoin, a yield token, or something else?",
      answer:
        "JLP is a yield-bearing LP/index token — NOT a stablecoin. It represents a basket (~35% stable, ~65% volatile: SOL/ETH/BTC/USDC/USDT) plus a claim on 75% of Jupiter Perps fees. Its price floats with the basket and compounds fees.",
      pinned: true,
    },
    {
      question: "How is JUP different from JLP?",
      answer:
        "JUP is the governance token of the Jupiter protocol (capped supply, deflationary via burns/buybacks). JLP is the liquidity-provider token for Jupiter Perps (uncapped, mint/redeem against the pool). Holding one does not give you the other.",
      pinned: true,
    },
    {
      question: "Where does JLP yield come from?",
      answer:
        "Real trading fees — open/close fees, borrow fees, price-impact, and swaps generated by perp traders. There are no token emissions; fees auto-compound into the pool, raising the JLP unit price.",
    },
    {
      question: "What is the JLP AUM cap?",
      answer:
        "The pool has a soft AUM cap (~$1.75B). When AUM hits the cap, new minting is disabled and JLP can trade at a premium to its virtual price on the open market.",
    },
  ],

  orgStructure: [
    {
      name: "Jupiter DAO",
      role: "Governance",
      description:
        "JUP holders vote on tokenomics, buybacks, treasury allocation, and major product decisions. Recent votes include 'Going Green' (net-zero emissions) and multi-billion-token burns.",
    },
    {
      name: "Jupiter Core Team",
      role: "Development",
      description:
        "Builds and operates Swap, Perps, and JLP. Founders (incl. 'Meow') have locked tokens through 2030 to align with long-term holders.",
    },
    {
      name: "Mercurial Heritage",
      role: "Legacy",
      description:
        "Jupiter spun out of the Mercurial stablecoin-AMM project; ~5% of supply traces to Mercurial stakeholder vesting, an active governance topic.",
    },
  ],

  tradFiComparison: [
    {
      product: "Index ETF (e.g. S&P 500)",
      similarity:
        "JLP behaves like a tokenized index fund — one token gives diversified exposure to a basket whose NAV drives its price.",
      differences:
        "JLP also earns a share of an exchange's trading fees and acts as the counterparty to leveraged traders; an ETF does neither.",
    },
    {
      product: "Market-maker / exchange equity",
      similarity:
        "JLP holders profit from trader flow and fees, similar to owning a slice of an exchange's trading desk.",
      differences:
        "JLP carries direct trader-PnL exposure (it loses when traders win) and has no equity claim or dividends.",
    },
    {
      product: "Governance share + buyback program",
      similarity: "JUP buybacks/burns resemble a company returning capital via repurchases.",
      differences:
        "Buybacks are protocol-revenue-funded and DAO-governed on-chain, not board-decided.",
    },
  ],

  risks: [
    {
      category: "Counterparty",
      description:
        "JLP is the counterparty to leveraged traders, so sustained trader profitability erodes JLP value.",
    },
    {
      category: "Collateral",
      description: "Top JLP holders control a large share of supply (top-10 ≈ 83%).",
    },
    {
      category: "Oracle",
      description:
        "Perps price off oracles; a faulty/stale feed can cause mispriced liquidations.",
    },
    {
      category: "Network",
      description:
        "Solana network congestion or outages can disrupt minting, redemption, and liquidations.",
    },
    {
      category: "Governance",
      description: "Emissions, burns, and buyback policy can change via DAO vote.",
    },
  ],

  investmentRounds: [
    {
      date: "2026-02-02",
      round: "Strategic (ParaFi)",
      amountUsd: 35_000_000,
      amountLabel: "$35M",
      investors: ["ParaFi Capital"],
      link: "https://solanafloor.com/news/jupiter-weighs-plan-to-drive-jup-token-emissions-to-net-zero",
    },
  ],

  partnerships: [
    {
      name: "21Shares (AJUP ETP)",
      date: "2025",
      amountLabel: null,
      description:
        "Regulated JUP exposure via a European exchange-traded product under ticker AJUP.",
    },
    {
      name: "Solana DEX network",
      date: "Ongoing",
      amountLabel: null,
      description:
        "Routes through Orca, Raydium, Meteora and others as the aggregation backbone.",
    },
  ],

  currentScale: {
    tvlUsd: 730_000_000,
    users: 64_400,
    aprPct: 42.0,
    targetAprPct: 60.0,
    marketCapUsd: null,
    loanPipelineUsd: null,
    partnerships: 12,
  },

  scaleLabels: {
    tvl: "JLP Pool AUM",
    users: "JLP Holders",
    apr: "JLP APY",
    partnerships: "Partnerships",
    coins: "Products under Jupiter",
  },

  memberCoins: [
    {
      slug: "jup",
      name: "Jupiter",
      symbol: "JUP",
      category: "Token",
      role: "DAO governance token (not a utility token)",
      subCategory: "Governance Token",
    },
    {
      slug: "jlp",
      name: "Jupiter Perps LP",
      symbol: "JLP",
      category: "Token",
      role: "Perps liquidity provider index + fee share",
      subCategory: "Yield-generating Token",
    },
    {
      slug: "jupusd",
      name: "JupUSD",
      symbol: "JUPUSD",
      category: "Stablecoin",
      role: "Reserve-backed dollar (no native yield)",
      subCategory: "Stablecoin",
    },
    {
      slug: "jljupusd",
      name: "Jupiter Lend JUPUSD",
      symbol: "jlJUPUSD",
      category: "Stablecoin",
      role: "Yield-bearing JupUSD from Lend Earn vault",
      subCategory: "Staked Stablecoin",
    },
    {
      slug: "jupsol",
      name: "JupSOL",
      symbol: "JUPSOL",
      category: "Token",
      role: "Jupiter Staked SOL liquid staking token",
      subCategory: "LST",
    },
  ],

  market: {
    priceUsd: {
      value: 0.16,
      dataSource: "live",
      sourceLabel: "Finance feed",
      updatedAt: NOW,
    },
    marketCapUsd: {
      value: 501_533_898,
      dataSource: "live",
      sourceLabel: "Finance feed",
      updatedAt: NOW,
    },
    change24hPct: { value: -13.26, dataSource: "live", updatedAt: NOW },
    high52w: { value: 0.68, dataSource: "live", updatedAt: NOW },
    low52w: { value: 0.11, dataSource: "live", updatedAt: NOW },
    maxSupply: { value: 10_000_000_000, dataSource: "live", updatedAt: NOW },
  },

  tokenomics: {
    maxSupply: 10_000_000_000,
    totalBurned: 3_000_000_000,
    buybackPolicy: "50% of on-chain revenue → open-market buybacks (>$70M in 2025).",
    emissionsPolicy: "'Going Green' proposal targets net-zero emissions for the remainder of 2026.",
    distribution: [
      { bucket: "Community", pct: 35 },
      { bucket: "Team", pct: 35 },
      { bucket: "Reserves/Other", pct: 30 },
    ],
    notes: [
      "Target total supply reduced toward ~5B via burns.",
      "Founder tokens locked through 2030.",
    ],
  },

  typedRisks: [
    {
      category: "Counterparty (trader PnL)",
      severity: "high",
      description:
        "JLP loses when leveraged traders win; net trader profitability is a structural drag.",
    },
    {
      category: "Holder concentration",
      severity: "medium",
      description: "A handful of addresses hold most JLP supply (top-10 ≈ 83%).",
    },
    {
      category: "Oracle",
      severity: "medium",
      description: "Perp pricing/liquidations depend on oracle integrity.",
    },
    {
      category: "Network (Solana)",
      severity: "medium",
      description: "Congestion/outages can block mint/redeem and liquidations.",
    },
    {
      category: "Governance/tokenomics",
      severity: "low",
      description: "DAO can alter burns, buybacks, and emissions.",
    },
  ],

  audits: [
    { firm: "OtterSec", date: "2024", url: null },
    { firm: "Sec3", date: "2024", url: null },
  ],

  timeline: jupiterTimeline,
  events: jupiterTimeline,

  sources: [
    { label: "Jupiter Dev Docs", url: "https://dev.jup.ag/docs" },
    {
      label: "SolanaFloor — Going Green",
      url: "https://solanafloor.com/news/jupiter-weighs-plan-to-drive-jup-token-emissions-to-net-zero",
    },
    {
      label: "Jupiter Research — Supply",
      url: "https://discuss.jup.ag/t/proposal-reduce-jup-token-supply-in-2026/36525",
    },
  ],

  agentSkill: {
    id: "jupiter.entity.v1",
    title: "Understanding Jupiter (Protocol Entity)",
    summary:
      "Jupiter is Solana's largest DeFi aggregator and vertically integrated exchange stack: Swap (aggregation), Perpetuals (100x leverage on SOL/ETH/BTC), and the JLP liquidity pool. JUP is the capped, deflationary governance token (10B max, burns + buybacks); JLP is the uncapped yield-bearing LP token for the perp pool. They are distinct products under one umbrella.",
    facts: [
      { key: "category", value: "DEX Aggregator | Perpetuals | Liquidity Hub" },
      { key: "chain", value: "Solana" },
      { key: "governance_token", value: "JUP (JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN)" },
      { key: "lp_token", value: "JLP (27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4)" },
      { key: "jup_max_supply", value: "10B (target ~5B via burns)" },
      { key: "jup_burned", value: "3B burned to date" },
      { key: "buyback_policy", value: "50% of on-chain revenue → open-market buybacks" },
      { key: "jlp_fee_share", value: "75% of perp fees to JLP holders" },
    ],
    sections: [
      {
        heading: "Product suite",
        body: "Jupiter Swap routes across Solana DEXs. Jupiter Perps offers oracle-based perpetuals counterparty to JLP. Limit orders and DCA round out the stack.",
      },
      {
        heading: "JUP vs JLP",
        body: "JUP governs the protocol and benefits from buybacks/burns. JLP represents pool basket exposure + fee yield. Holding JUP does not grant JLP exposure or vice versa.",
      },
      {
        heading: "Tokenomics",
        body: "'Going Green' targets net-zero JUP emissions in 2026. Founder tokens locked through 2030. Mercurial heritage affects ~5% vesting.",
      },
      {
        heading: "Key risks",
        body: "Trader-PnL counterparty risk on JLP, oracle dependence, Solana network risk, governance shifts on JUP tokenomics.",
      },
    ],
    actions: [
      {
        name: "Get JUP governance state",
        description: "Read current JUP supply, burns, and buyback totals.",
        signature: "getJupGovernanceState() -> { maxSupply, burned, buybackTotalUsd }",
        readOnly: true,
      },
      {
        name: "Get protocol revenue",
        description: "Read aggregated Jupiter on-chain revenue metrics.",
        signature: "getProtocolRevenue() -> { revenue24hUsd, buybackPct }",
        readOnly: true,
      },
      {
        name: "List Jupiter products",
        description: "Enumerate active Jupiter product modules.",
        signature: "listJupiterProducts() -> Product[]",
        readOnly: true,
      },
    ],
    glossary: [
      { term: "Going Green", definition: "DAO proposal targeting net-zero JUP emissions." },
      { term: "Jupuary", definition: "Annual JUP airdrop/distribution event." },
    ],
    sources: [
      { label: "Jupiter Dev Docs", url: "https://dev.jup.ag/docs" },
      {
        label: "SolanaFloor — Going Green",
        url: "https://solanafloor.com/news/jupiter-weighs-plan-to-drive-jup-token-emissions-to-net-zero",
      },
    ],
    version: "1.0.0",
    updatedAt: NOW,
  },

  arbitrumPortalMetadata: {
    portalUrl: null,
    logoUrl: null,
    bannerUrl: null,
    chains: ["Solana"],
    subCategory: "DEX Aggregator | Perpetuals",
    isLive: true,
    isArbitrumNative: false,
    isPubliclyAudited: true,
    foundedDate: "2021-01-01",
  },
  createdAt: NOW,
  updatedAt: NOW,
};
