// GENERATED by scripts/generate-credit-partnership-model.mjs — do not hand-edit.
// Tiny on purpose: lib/networks/tabs.ts gates the Partnerships tab on this
// list without pulling the full partnership model into its chunk.

/** The 14 Credit entities covered by the M9 partnership dataset (CAN-81).
 * The 8 outstanding Credit entities are parked to M11 pending CAN-48 tags. */
export const PARTNERSHIP_COVERED_SLUGS: readonly string[] = [
  "aave",
  "compound",
  "morpho",
  "radiant",
  "spark",
  "extra-finance",
  "fluid",
  "gearbox",
  "stella",
  "maple",
  "notional",
  "pendle",
  "sense",
  "spectra"
];
