// GENERATED by scripts/generate-credit-competitor-model.mjs — do not hand-edit.
// Source: scripts/data/credit-m8-store-patch.json (parsed from the M8
// competitor dataset compiled 2026-07-26). Reciprocity is closed at
// parse time and asserted at store level by scripts/verify-m8-reciprocity.mjs.
// Nodes + edges are shaped for M9's RelationshipExplorer (later consumer).

export type CreditCompetitorTag = "Lending" | "Leveraged Yield" | "Fixed Income";

export interface CompetitorNode {
  slug: string;
  name: string;
  tag: CreditCompetitorTag;
  entityType: "protocol" | "risk-curator";
  /** t3tris-finance: provisional Leveraged Yield fit (dataset flag). */
  tagFit?: "partial";
  /** boros -> "pendle": shared parent; never render the pair as plain rivals. */
  parentSlug?: string;
  /** Winding down / sunset / dormant (entityStatus overrides carry the label). */
  nonSteadyState?: boolean;
  /** "not-applicable" = curator with no contracts (Steakhouse); "unverified" =
   * zero audits in DefiLlama's record, an open verification item NOT a finding. */
  auditStatus: "audited" | "unverified" | "not-applicable";
  dataQualityFlags?: string[];
}

export interface CompetitorEdge {
  /** Sorted pair (a < b); reciprocity is closed by construction. */
  a: string;
  b: string;
  sharedTag: boolean;
  /** boros|pendle only: same team and brand. */
  sharedParent?: boolean;
  /** Pair is simultaneously partner and competitor (CAN-84 comment). */
  alsoPartner?: boolean;
}

export interface TierBRow {
  name: string;
  type: string;
  competesWithTags: CreditCompetitorTag[];
  /** Off-platform: never clickable. */
  note: string;
}

/** Committed per-tag cohorts (percentile denominators). NOT profile.tags. */
export const TAG_COHORTS: Record<CreditCompetitorTag, string[]> = {
  "Lending": [
    "aave",
    "compound",
    "morpho",
    "radiant",
    "spark",
    "steakhouse-financial",
    "native-credit-pool",
    "dolomite",
    "euler",
    "csigma-finance",
    "liquity",
    "curve-stablecoin"
  ],
  "Leveraged Yield": [
    "extra-finance",
    "fluid",
    "gearbox",
    "stella",
    "t3tris-finance",
    "contango",
    "yield-basis",
    "origami-finance",
    "deltaprime"
  ],
  "Fixed Income": [
    "maple",
    "notional",
    "pendle",
    "sense",
    "spectra",
    "termmax",
    "term-finance",
    "boros",
    "fira",
    "exactly",
    "inverse-finance"
  ]
};

/** CAN-73 risk-comparison cohorts: only the 14 entities with TypedRisks.
 * Composites are never compared across tags (docs/credit/risk-taxonomy.md). */
export const RISK_COHORTS: Record<CreditCompetitorTag, string[]> = {
  "Lending": [
    "aave",
    "compound",
    "morpho",
    "radiant",
    "spark"
  ],
  "Leveraged Yield": [
    "extra-finance",
    "fluid",
    "gearbox",
    "stella"
  ],
  "Fixed Income": [
    "maple",
    "notional",
    "pendle",
    "sense",
    "spectra"
  ]
};

export const COMPETITOR_NODES: Record<string, CompetitorNode> = {
  "aave": {"slug":"aave","name":"Aave","tag":"Lending","entityType":"protocol","auditStatus":"audited"},
  "boros": {"slug":"boros","name":"Boros","tag":"Fixed Income","entityType":"protocol","parentSlug":"pendle","auditStatus":"unverified"},
  "compound": {"slug":"compound","name":"Compound","tag":"Lending","entityType":"protocol","auditStatus":"audited"},
  "contango": {"slug":"contango","name":"Contango V2","tag":"Leveraged Yield","entityType":"protocol","auditStatus":"audited"},
  "csigma-finance": {"slug":"csigma-finance","name":"cSigma Finance","tag":"Lending","entityType":"protocol","auditStatus":"audited"},
  "curve-stablecoin": {"slug":"curve-stablecoin","name":"Curve (crvUSD)","tag":"Lending","entityType":"protocol","auditStatus":"unverified"},
  "deltaprime": {"slug":"deltaprime","name":"DeltaPrime","tag":"Leveraged Yield","entityType":"protocol","auditStatus":"audited"},
  "dolomite": {"slug":"dolomite","name":"Dolomite","tag":"Lending","entityType":"protocol","auditStatus":"audited"},
  "euler": {"slug":"euler","name":"Euler V2","tag":"Lending","entityType":"protocol","auditStatus":"audited"},
  "exactly": {"slug":"exactly","name":"Exactly","tag":"Fixed Income","entityType":"protocol","auditStatus":"audited"},
  "extra-finance": {"slug":"extra-finance","name":"Extra Finance","tag":"Leveraged Yield","entityType":"protocol","auditStatus":"audited"},
  "fira": {"slug":"fira","name":"Fira","tag":"Fixed Income","entityType":"protocol","auditStatus":"audited","dataQualityFlags":["DefiLlama borrowed figure ($429.7m) vastly exceeds supplied TVL; unverified"]},
  "fluid": {"slug":"fluid","name":"Fluid","tag":"Leveraged Yield","entityType":"protocol","auditStatus":"audited"},
  "gearbox": {"slug":"gearbox","name":"Gearbox","tag":"Leveraged Yield","entityType":"protocol","auditStatus":"audited"},
  "inverse-finance": {"slug":"inverse-finance","name":"Inverse Finance","tag":"Fixed Income","entityType":"protocol","auditStatus":"unverified"},
  "liquity": {"slug":"liquity","name":"Liquity","tag":"Lending","entityType":"protocol","auditStatus":"unverified"},
  "maple": {"slug":"maple","name":"Maple Finance","tag":"Fixed Income","entityType":"protocol","auditStatus":"audited"},
  "morpho": {"slug":"morpho","name":"Morpho","tag":"Lending","entityType":"protocol","auditStatus":"audited"},
  "native-credit-pool": {"slug":"native-credit-pool","name":"Native","tag":"Lending","entityType":"protocol","auditStatus":"unverified"},
  "notional": {"slug":"notional","name":"Notional Finance","tag":"Fixed Income","entityType":"protocol","nonSteadyState":true,"auditStatus":"audited"},
  "origami-finance": {"slug":"origami-finance","name":"Origami Finance","tag":"Leveraged Yield","entityType":"protocol","auditStatus":"audited"},
  "pendle": {"slug":"pendle","name":"Pendle Finance","tag":"Fixed Income","entityType":"protocol","auditStatus":"audited"},
  "radiant": {"slug":"radiant","name":"Radiant Capital","tag":"Lending","entityType":"protocol","nonSteadyState":true,"auditStatus":"audited"},
  "sense": {"slug":"sense","name":"Sense Finance","tag":"Fixed Income","entityType":"protocol","nonSteadyState":true,"auditStatus":"audited"},
  "spark": {"slug":"spark","name":"Spark Protocol","tag":"Lending","entityType":"protocol","auditStatus":"audited"},
  "spectra": {"slug":"spectra","name":"Spectra","tag":"Fixed Income","entityType":"protocol","auditStatus":"audited"},
  "steakhouse-financial": {"slug":"steakhouse-financial","name":"Steakhouse Financial","tag":"Lending","entityType":"risk-curator","auditStatus":"not-applicable","dataQualityFlags":["TVL books under Morpho, Euler and Kamino vaults"]},
  "stella": {"slug":"stella","name":"Stella","tag":"Leveraged Yield","entityType":"protocol","nonSteadyState":true,"auditStatus":"audited"},
  "t3tris-finance": {"slug":"t3tris-finance","name":"T3tris Finance","tag":"Leveraged Yield","entityType":"protocol","tagFit":"partial","auditStatus":"audited"},
  "term-finance": {"slug":"term-finance","name":"Term Finance","tag":"Fixed Income","entityType":"protocol","auditStatus":"unverified"},
  "termmax": {"slug":"termmax","name":"TermMax","tag":"Fixed Income","entityType":"protocol","auditStatus":"audited"},
  "yield-basis": {"slug":"yield-basis","name":"Yield Basis","tag":"Leveraged Yield","entityType":"protocol","auditStatus":"unverified"},
};

export const COMPETITOR_EDGES: CompetitorEdge[] = [
  {"a":"aave","b":"compound","sharedTag":true},
  {"a":"aave","b":"contango","sharedTag":false},
  {"a":"aave","b":"dolomite","sharedTag":true},
  {"a":"aave","b":"euler","sharedTag":true},
  {"a":"aave","b":"exactly","sharedTag":false},
  {"a":"aave","b":"fluid","sharedTag":false},
  {"a":"aave","b":"gearbox","sharedTag":false},
  {"a":"aave","b":"justlend","sharedTag":false},
  {"a":"aave","b":"kamino","sharedTag":false},
  {"a":"aave","b":"maple","sharedTag":false,"alsoPartner":true},
  {"a":"aave","b":"morpho","sharedTag":true},
  {"a":"aave","b":"notional","sharedTag":false},
  {"a":"aave","b":"radiant","sharedTag":true},
  {"a":"aave","b":"spark","sharedTag":true},
  {"a":"aave","b":"usd-ai","sharedTag":false},
  {"a":"aave","b":"venus","sharedTag":false},
  {"a":"boros","b":"notional","sharedTag":true},
  {"a":"boros","b":"pendle","sharedTag":true,"sharedParent":true},
  {"a":"boros","b":"sense","sharedTag":true},
  {"a":"centrifuge","b":"clearpool","sharedTag":false},
  {"a":"centrifuge","b":"goldfinch","sharedTag":false},
  {"a":"clearpool","b":"csigma-finance","sharedTag":false},
  {"a":"clearpool","b":"goldfinch","sharedTag":false},
  {"a":"clearpool","b":"native-credit-pool","sharedTag":false},
  {"a":"compound","b":"euler","sharedTag":true},
  {"a":"compound","b":"morpho","sharedTag":true},
  {"a":"compound","b":"radiant","sharedTag":true},
  {"a":"contango","b":"gearbox","sharedTag":true},
  {"a":"contango","b":"stella","sharedTag":true},
  {"a":"csigma-finance","b":"goldfinch","sharedTag":false},
  {"a":"csigma-finance","b":"maple","sharedTag":false},
  {"a":"curve-stablecoin","b":"liquity","sharedTag":true},
  {"a":"curve-stablecoin","b":"morpho","sharedTag":true},
  {"a":"curve-stablecoin","b":"sky","sharedTag":false},
  {"a":"curve-stablecoin","b":"yield-basis","sharedTag":false},
  {"a":"deltaprime","b":"extra-finance","sharedTag":true},
  {"a":"deltaprime","b":"gearbox","sharedTag":true},
  {"a":"deltaprime","b":"stella","sharedTag":true},
  {"a":"dolomite","b":"fluid","sharedTag":false},
  {"a":"dolomite","b":"radiant","sharedTag":true},
  {"a":"euler","b":"morpho","sharedTag":true},
  {"a":"exactly","b":"notional","sharedTag":true},
  {"a":"exactly","b":"pendle","sharedTag":true},
  {"a":"extra-finance","b":"gearbox","sharedTag":true},
  {"a":"extra-finance","b":"origami-finance","sharedTag":true},
  {"a":"extra-finance","b":"stella","sharedTag":true},
  {"a":"extra-finance","b":"t3tris-finance","sharedTag":true},
  {"a":"fira","b":"notional","sharedTag":true},
  {"a":"fira","b":"pendle","sharedTag":true},
  {"a":"fira","b":"spectra","sharedTag":true},
  {"a":"fluid","b":"gearbox","sharedTag":true},
  {"a":"fluid","b":"morpho","sharedTag":false},
  {"a":"gearbox","b":"morpho","sharedTag":false},
  {"a":"gearbox","b":"origami-finance","sharedTag":true},
  {"a":"gearbox","b":"stella","sharedTag":true},
  {"a":"gearbox","b":"t3tris-finance","sharedTag":true},
  {"a":"gearbox","b":"yield-basis","sharedTag":true},
  {"a":"inverse-finance","b":"liquity","sharedTag":false},
  {"a":"inverse-finance","b":"notional","sharedTag":true},
  {"a":"inverse-finance","b":"pendle","sharedTag":true},
  {"a":"justlend","b":"venus","sharedTag":false},
  {"a":"kamino","b":"morpho","sharedTag":false},
  {"a":"liquity","b":"sky","sharedTag":false},
  {"a":"maple","b":"morpho","sharedTag":false,"alsoPartner":true},
  {"a":"maple","b":"native-credit-pool","sharedTag":false},
  {"a":"maple","b":"steakhouse-financial","sharedTag":false},
  {"a":"maple","b":"term-finance","sharedTag":true},
  {"a":"maple","b":"usd-ai","sharedTag":false},
  {"a":"morpho","b":"native-credit-pool","sharedTag":true},
  {"a":"morpho","b":"spark","sharedTag":true},
  {"a":"morpho","b":"steakhouse-financial","sharedTag":true},
  {"a":"notional","b":"pendle","sharedTag":true,"alsoPartner":true},
  {"a":"notional","b":"sense","sharedTag":true},
  {"a":"notional","b":"spectra","sharedTag":true},
  {"a":"notional","b":"term-finance","sharedTag":true},
  {"a":"notional","b":"termmax","sharedTag":true},
  {"a":"origami-finance","b":"stella","sharedTag":true},
  {"a":"pendle","b":"sense","sharedTag":true},
  {"a":"pendle","b":"spectra","sharedTag":true},
  {"a":"pendle","b":"term-finance","sharedTag":true},
  {"a":"pendle","b":"termmax","sharedTag":true},
  {"a":"radiant","b":"venus","sharedTag":false},
  {"a":"sense","b":"spectra","sharedTag":true},
  {"a":"sky","b":"spark","sharedTag":false},
  {"a":"spark","b":"steakhouse-financial","sharedTag":true},
  {"a":"spectra","b":"termmax","sharedTag":true},
  {"a":"stella","b":"t3tris-finance","sharedTag":true},
  {"a":"stella","b":"yield-basis","sharedTag":true},
];

/** Off-platform competitors (CeFi, tokenised treasuries, benchmarks, non-EVM). */
export const TIER_B_ROWS: TierBRow[] = [
  {"name":"Tether (lending arm)","type":"CeFi lender","competesWithTags":["Lending"],"note":"62.25% share of tracked CeFi lending, Q1 2026"},
  {"name":"Nexo","type":"CeFi lender","competesWithTags":["Lending"],"note":"7.02% CeFi market share Q1 2026"},
  {"name":"Coinbase crypto-backed loans","type":"CeFi lender","competesWithTags":["Lending"],"note":"Loan book grew $90.04m in Q1 2026, distributes Steakhouse-curated Morpho USDC lending to retail"},
  {"name":"Galaxy Digital lending desk","type":"CeFi lender","competesWithTags":["Lending"],"note":"Contracted 21% in Q1 2026"},
  {"name":"Ledn","type":"CeFi lender, BTC","competesWithTags":["Lending"],"note":"Historically third-largest CeFi lender"},
  {"name":"CeFi lending market aggregate","type":"Market benchmark","competesWithTags":["Lending"],"note":"Loan books fell 6% QoQ to $23.3bn in Q1 2026, first contraction since Q3 2024"},
  {"name":"BlackRock BUIDL","type":"Tokenised treasury fund","competesWithTags":["Fixed Income"],"note":"$2.61bn as of 26 July 2026"},
  {"name":"Circle USYC","type":"Tokenised treasury","competesWithTags":["Fixed Income"],"note":"$3.00bn as of 26 July 2026"},
  {"name":"Ondo USDY","type":"Tokenised treasury note","competesWithTags":["Fixed Income"],"note":"$2.16bn as of 26 July 2026"},
  {"name":"Ondo OUSG","type":"Tokenised short-term government bond fund","competesWithTags":["Fixed Income"],"note":"$481m as of 26 July 2026"},
  {"name":"Franklin Templeton BENJI","type":"Tokenised money market fund","competesWithTags":["Fixed Income"],"note":"$735m as of 26 July 2026, SEC-registered"},
  {"name":"Tokenised US Treasuries aggregate","type":"Market benchmark","competesWithTags":["Fixed Income"],"note":"$16.20bn across 85 products as of 26 July 2026"},
  {"name":"Kamino Finance","type":"Non-EVM lending protocol, Solana","competesWithTags":["Lending","Leveraged Yield"],"note":"Roughly $3.2bn TVL, the main non-EVM benchmark"},
  {"name":"Save, MarginFi, Drift","type":"Non-EVM lending protocols, Solana","competesWithTags":["Lending"],"note":"Drove Solana past $2.1bn of active loans in May 2026"},
  {"name":"Jupiter Lend and Project 0 Prime","type":"Non-EVM lending infrastructure, Solana","competesWithTags":["Lending"],"note":"Prime engine covers roughly 98% of Solana lending TVL"},
];

/** Total tagged Credit entities across the three cohorts. */
export const CREDIT_TAGGED_TOTAL = 32;
