// GENERATED by scripts/fetch-credit-comparables.mjs — do not hand-edit.
// Snapshot of comparable metrics for the 32 tagged Credit entities
// (percentile-bar inputs, CAN-87). Source: api.llama.fi/protocol/<slug>
// (multi-slug entities summed), with the committed M8 dataset (compiled
// 2026-07-26) as fallback where a fetch failed. Re-run to refresh; every
// consumer must surface asOf.
//
// utilizationPct is ONLY ever protocol-reported and is null this pass: it is
// NEVER computed as borrowed/supplied (DefiLlama nets borrowed collateral out
// of supplied for dolomite, contango, origami-finance, euler and fira). No
// APY fields exist: no source covers the whole cohort. fira's borrowed figure
// is withheld as a data-quality flag.

export interface CreditComparable {
  slug: string;
  tvlUsd: number | null;
  totalBorrowedUsd: number | null;
  /** Protocol-reported only; never derived. Null this pass. */
  utilizationPct: number | null;
  chainCount: number | null;
  /** DefiLlama listing date ("Listed since"), not protocol genesis. */
  launchDate: string | null;
  /** Known audits count (store or dataset); null = unverified, not zero. */
  auditCount: number | null;
  asOf: string;
  source: "defillama-snapshot" | "m8-dataset";
}

export const CREDIT_COMPARABLES: Record<string, CreditComparable> = {
  "aave": {"slug":"aave","tvlUsd":14225422313,"totalBorrowedUsd":10954951901,"utilizationPct":null,"chainCount":22,"launchDate":"2022-04-01","auditCount":6,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "boros": {"slug":"boros","tvlUsd":7861783,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":1,"launchDate":"2025-08-07","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "compound": {"slug":"compound","tvlUsd":1249925460,"totalBorrowedUsd":571359523,"utilizationPct":null,"chainCount":9,"launchDate":"2022-09-14","auditCount":2,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "contango": {"slug":"contango","tvlUsd":6158408,"totalBorrowedUsd":44266567,"utilizationPct":null,"chainCount":10,"launchDate":"2023-10-06","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "csigma-finance": {"slug":"csigma-finance","tvlUsd":12657543,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":4,"launchDate":"2025-03-10","auditCount":2,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "curve-stablecoin": {"slug":"curve-stablecoin","tvlUsd":133261393,"totalBorrowedUsd":41650097,"utilizationPct":null,"chainCount":4,"launchDate":"2023-05-03","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "deltaprime": {"slug":"deltaprime","tvlUsd":3594981,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":2,"launchDate":"2023-01-30","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "dolomite": {"slug":"dolomite","tvlUsd":248680828,"totalBorrowedUsd":274744998,"utilizationPct":null,"chainCount":7,"launchDate":"2022-10-17","auditCount":2,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "euler": {"slug":"euler","tvlUsd":328865229,"totalBorrowedUsd":605224558,"utilizationPct":null,"chainCount":16,"launchDate":"2024-08-26","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "exactly": {"slug":"exactly","tvlUsd":4719274,"totalBorrowedUsd":850889,"utilizationPct":null,"chainCount":3,"launchDate":"2022-12-24","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "extra-finance": {"slug":"extra-finance","tvlUsd":26321567,"totalBorrowedUsd":737734,"utilizationPct":null,"chainCount":3,"launchDate":"2023-05-14","auditCount":3,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "fira": {"slug":"fira","tvlUsd":16598214,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":1,"launchDate":"2026-01-27","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "fluid": {"slug":"fluid","tvlUsd":807706031,"totalBorrowedUsd":763011946,"utilizationPct":null,"chainCount":5,"launchDate":null,"auditCount":7,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "gearbox": {"slug":"gearbox","tvlUsd":18963971,"totalBorrowedUsd":10406479,"utilizationPct":null,"chainCount":11,"launchDate":"2021-12-27","auditCount":5,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "inverse-finance": {"slug":"inverse-finance","tvlUsd":19330945,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":1,"launchDate":"2023-01-13","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "liquity": {"slug":"liquity","tvlUsd":77909533,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":1,"launchDate":"2025-01-23","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "maple": {"slug":"maple","tvlUsd":2324649823,"totalBorrowedUsd":1759659765,"utilizationPct":null,"chainCount":2,"launchDate":null,"auditCount":5,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "morpho": {"slug":"morpho","tvlUsd":7674149431,"totalBorrowedUsd":4087786172,"utilizationPct":null,"chainCount":41,"launchDate":"2024-01-14","auditCount":3,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "native-credit-pool": {"slug":"native-credit-pool","tvlUsd":37936813,"totalBorrowedUsd":16968757,"utilizationPct":null,"chainCount":7,"launchDate":"2024-05-23","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "notional": {"slug":"notional","tvlUsd":3097190,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":2,"launchDate":"2023-11-14","auditCount":10,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "origami-finance": {"slug":"origami-finance","tvlUsd":49394648,"totalBorrowedUsd":67218878,"utilizationPct":null,"chainCount":3,"launchDate":"2024-05-13","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "pendle": {"slug":"pendle","tvlUsd":1202534286,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":12,"launchDate":null,"auditCount":3,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "radiant": {"slug":"radiant","tvlUsd":626940,"totalBorrowedUsd":217736,"utilizationPct":null,"chainCount":4,"launchDate":"2023-03-21","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "sense": {"slug":"sense","tvlUsd":24063,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":1,"launchDate":"2022-09-19","auditCount":5,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "spark": {"slug":"spark","tvlUsd":4738632565,"totalBorrowedUsd":1865552014,"utilizationPct":null,"chainCount":9,"launchDate":null,"auditCount":2,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "spectra": {"slug":"spectra","tvlUsd":32147017,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":12,"launchDate":"2024-06-05","auditCount":3,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "steakhouse-financial": {"slug":"steakhouse-financial","tvlUsd":2414886136,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":9,"launchDate":"2025-05-20","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "stella": {"slug":"stella","tvlUsd":442829,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":1,"launchDate":"2023-06-22","auditCount":2,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "t3tris-finance": {"slug":"t3tris-finance","tvlUsd":11869320,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":2,"launchDate":"2026-06-25","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "term-finance": {"slug":"term-finance","tvlUsd":13860050,"totalBorrowedUsd":1666828,"utilizationPct":null,"chainCount":6,"launchDate":"2023-08-16","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "termmax": {"slug":"termmax","tvlUsd":34509602,"totalBorrowedUsd":26302820,"utilizationPct":null,"chainCount":8,"launchDate":"2024-06-20","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
  "yield-basis": {"slug":"yield-basis","tvlUsd":134602116,"totalBorrowedUsd":null,"utilizationPct":null,"chainCount":1,"launchDate":"2025-09-25","auditCount":null,"asOf":"2026-07-27","source":"defillama-snapshot"},
};
