// GENERATED by scripts/generate-shared-risk-drivers.mjs — do not hand-edit.
// Source: scripts/data/credit-assets-risks.json (shared_risk_drivers,
// compiled 2026-07-26). Risk drivers appearing in 3+ of the
// 14 in-scope Credit entities' risk tables; `audit` marks
// audit/bounty firms (dataset: weaker signal, render as a secondary group).

export interface SharedRiskDriver {
  kind: "asset" | "counterparty";
  label: string;
  /** How many of the 14 in-scope Credit entities carry this driver. */
  entityCount: number;
  entities: string[];
  /** Audit/bounty firm — weaker signal than a shared oracle or issuer. */
  audit: boolean;
}

/** Keyed by UPPERCASE driver label (join key for linkedAssets/linkedPartners). */
export const SHARED_RISK_DRIVERS: Record<string, SharedRiskDriver> = {
  "USDC": { kind: "asset", label: "USDC", entityCount: 7, entities: ["aave","compound","extra-finance","gearbox","notional","radiant","spark"], audit: false },
  "IMMUNEFI": { kind: "counterparty", label: "Immunefi", entityCount: 7, entities: ["extra-finance","fluid","gearbox","maple","notional","pendle","sense"], audit: true },
  "WETH": { kind: "asset", label: "WETH", entityCount: 6, entities: ["aave","compound","extra-finance","gearbox","radiant","spark"], audit: false },
  "CHAINLINK": { kind: "counterparty", label: "Chainlink", entityCount: 6, entities: ["compound","extra-finance","gearbox","maple","morpho","spark"], audit: false },
  "LIDO": { kind: "counterparty", label: "Lido", entityCount: 6, entities: ["aave","compound","gearbox","notional","pendle","spark"], audit: false },
  "USDT": { kind: "asset", label: "USDT", entityCount: 5, entities: ["aave","compound","gearbox","spark","stella"], audit: false },
  "WSTETH": { kind: "asset", label: "wstETH", entityCount: 5, entities: ["aave","compound","gearbox","notional","spark"], audit: false },
  "PECKSHIELD": { kind: "counterparty", label: "PeckShield", entityCount: 5, entities: ["extra-finance","fluid","radiant","sense","stella"], audit: true },
  "PENDLE": { kind: "counterparty", label: "Pendle", entityCount: 5, entities: ["aave","gearbox","morpho","spark","stella"], audit: false },
  "ARBITRUM": { kind: "counterparty", label: "Arbitrum", entityCount: 4, entities: ["fluid","gearbox","spectra","stella"], audit: false },
  "MORPHO": { kind: "counterparty", label: "Morpho", entityCount: 4, entities: ["notional","pendle","spark","spectra"], audit: false },
  "SHERLOCK": { kind: "counterparty", label: "Sherlock", entityCount: 4, entities: ["extra-finance","notional","sense","spectra"], audit: true },
  "SKY": { kind: "counterparty", label: "Sky", entityCount: 4, entities: ["fluid","gearbox","maple","spark"], audit: false },
  "RSETH": { kind: "asset", label: "rsETH", entityCount: 3, entities: ["aave","gearbox","spark"], audit: false },
  "WBTC": { kind: "asset", label: "WBTC", entityCount: 3, entities: ["compound","spark","stella"], audit: false },
  "AAVE": { kind: "counterparty", label: "Aave", entityCount: 3, entities: ["maple","notional","pendle"], audit: false },
  "CHAINLINK CCIP": { kind: "counterparty", label: "Chainlink CCIP", entityCount: 3, entities: ["aave","fluid","maple"], audit: false },
  "CHAINSECURITY": { kind: "counterparty", label: "ChainSecurity", entityCount: 3, entities: ["aave","gearbox","pendle"], audit: true },
  "CURVE": { kind: "counterparty", label: "Curve", entityCount: 3, entities: ["fluid","sense","spark"], audit: false },
  "LAYERZERO": { kind: "counterparty", label: "LayerZero", entityCount: 3, entities: ["aave","extra-finance","spark"], audit: false },
  "OPENZEPPELIN": { kind: "counterparty", label: "OpenZeppelin", entityCount: 3, entities: ["compound","radiant","stella"], audit: true },
  "REDSTONE": { kind: "counterparty", label: "RedStone", entityCount: 3, entities: ["fluid","gearbox","spark"], audit: false },
};

/** Total in-scope Credit entities the counts are out of. */
export const SHARED_DRIVER_ENTITY_TOTAL = 14;
